export const GET_TAGS_REQUEST='GET_TAGS_REQUEST'
export const GET_TAGS_SUCCESS='GET_TAGS_SUCCESS'
export const GET_TAGS_FAILURE='GET_TAGS_FAILURE'


export const POST_TAGS_REQUEST='POST_TAGS_REQUEST'
export const POST_TAGS_SUCCESS='POST_TAGS_SUCCESS'
export const POST_TAGS_FAILURE='POST_TAGS_FAILURE'